services:

  db:
    container_name: form_db
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      TZ: Asia/Bangkok
    volumes:
      - database_data:/var/lib/mysql
    networks:
      - form-network

volumes:
  database_data:
networks:
  form-network:
    driver: bridge
